name: Auto Update

on:
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Update All Modpacks
        run: |
          # Vanilla Modpacks
          vpacks=(
              re-console
              re-console-lite
          )
          # Platform Version
          pfvs=(
              curseforge
              modrinth
          )
          # Mod Loader Version
          mlvs=(
              fabric
          )
          # Minecraft Version
          mcvs=(
              1.20.1
              1.20.4
              1.21.1
              1.21.3
              1.21.4
              1.21.5
              1.21.8
          )

          for i in "${vpacks[@]}"; do
              for q in "${pfvs[@]}"; do
                  for w in "${mlvs[@]}"; do
                      for e in "${mcvs[@]}"; do
                          DIR="./versions/vanilla/src/$i/$q/$w/$e"
                          if [ -d "$DIR" ]; then
                              echo
                              echo "Updating $i $q $w $e"
                              (cd $DIR && packwiz refresh -y && packwiz update -a -y)
                          fi
                      done
                  if [ -d "./versions/vanilla/src/$i/$q/$w" ]; then
                      echo
                      echo "Waiting 20s for rate-limiting"
                      echo
                      sleep 20
                  fi
                  done
              done
          done

      - name: Commit Updates
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
